name: 空气质量
on:
  push:
    branches: 
      - main
  schedule:
    - cron: '*/2 * * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule

# on:
#   push:
#   schedule:
#     - cron: '*/1 * * * *' # 每5分钟一次，测试用

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run aqi' # 步骤二，执行sh命令文件
        run: bash ./aqi.sh
