name: 激活&签到

on:
    workflow_dispatch:
    schedule:
        - cron: "0 1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: main

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run checkin'
        run: bash ./checkin.sh
