name: 激活

on:
    workflow_dispatch:
    schedule:
        - cron: "*/1 * * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: 'Checkout codes'
            - name: Run active
              run: |
                  /bin/bash active.sh
